id = "jsp"
name = "JSP"
description = "JSP support."
version = "0.2.0"
schema_version = 1
authors = ["Riccardo Strina <riccardo.strina@icloud.com>"]
repository = "https://github.com/tartarughina/zed-jsp"

[grammars.jsp]
repository = "https://github.com/tartarughina/tree-sitter-jsp"
commit = "6d2b70595a20e15f95666d4162da36caf5881795"

[grammars.el]
repository = "https://github.com/tartarughina/tree-sitter-el"
commit = "0a710ca2640d11b7d06c9eb188d6c581f1303ef9"
